/**
 *
 * Copyright 2008 (C) The original author or authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.livetribe.slp.osgi;

import java.util.Dictionary;

import org.livetribe.slp.sa.StandardServiceAgentServer;
import org.osgi.service.cm.ConfigurationException;
import org.osgi.service.cm.ManagedService;
import org.osgi.service.cm.ManagedServiceFactory;


/**
 * @version $Revision$ $Date$
 */
public class StandardServiceAgentService implements ManagedService, ManagedServiceFactory
{
    public void updated(Dictionary dictionary) throws ConfigurationException
    {
        StandardServiceAgentServer server = StandardServiceAgentServer.newInstance(DictionarySettings.from(dictionary));
        //todo: consider this autogenerated code
    }

    public String getName()
    {
        return null;  //todo: consider this autogenerated code
    }

    public void updated(String s, Dictionary dictionary) throws ConfigurationException
    {
        //todo: consider this autogenerated code
    }

    public void deleted(String s)
    {
        //todo: consider this autogenerated code
    }
}
